# Dockerfile for Flask app
#stage 1 - build the model
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# stage 2 - build the flask app and copy the model
# Copy Flask app files
FROM python:3.10-slim
WORKDIR /app
COPY House_Price_Prediction.py .
COPY model_api.py .

RUN python House_Price_Prediction.py --train


# Expose port
EXPOSE 6000

# Run the Flask app
CMD ["python", "model_api.py"]
