# Stage 1: Build stage
FROM python:3.9-slim AS builder

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Runtime stage
FROM python:3.9-slim

WORKDIR /app

# Copy installed dependencies from builder stage
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy project files
COPY House_Price_Prediction.py model_api.py ./

# Train ML model
RUN python House_Price_Prediction.py --train

EXPOSE 6000

# Start Flask app
CMD ["python", "model_api.py"]
