name: Run Colab Notebook

on: 
  push:
    branches:
      - dev01
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install papermill colab-cli

    - name: Run Notebook on Google Colab
      run: |
        colab-cli execute ./model_file/BTD.ipynb --output output.ipynb

    - name: Commit and Push Output Notebook
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add output.ipynb
        git commit -m "Updated output notebook"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
