name: Run Colab Notebook

on: 
  push:
    branches:
      - dev01
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        pip install colab-cli

    - name: Run Notebook on Google Colab
      run: |
        colab-cli execute ./model_file/BTD.ipynb
