name: Deploy Model and Flask App

on:
  workflow_dispatch:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated version

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -f Dockerfile.flask-app -t ${{ secrets.DOCKER_USERNAME }}/flask-app:v0.7 .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:v0.7
