name: Deploy Model and Flask App

on:
  workflow_dispatch:  # Trigger pipeline manually

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  setup_docker_and_configure_buildx:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Clear old Docker credentials
      run: rm -f ~/.docker/config.json
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Install Docker Compose
      run: |
        DOCKER_COMPOSE_VERSION=2.20.2
        sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

  build_image:
    runs-on: ubuntu-latest
    needs: setup_docker_and_configure_buildx
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Image for model and Flask App
      run: |
        docker build -f Dockerfile.flask-app -t ${{ secrets.DOCKER_USERNAME }}/flask-app:v0.7 .

    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:v0.7
