name: Deploy Model and Flask App

on:
  push:
    tags:
      - "v*"  # Triggers only when a version tag like "v1.0.0" is pushed

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated version

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Extract Git Tag
      id: get_tag
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -f Dockerfile.brain-tumor-predictor -t ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:v0.7 .
    #     docker push ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:v0.7

    - name: Build and Push Docker Image (Versioned + Latest)
      run: |
        docker build -f Dockerfile.brain-tumor-predictor -t ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:${{ env.IMAGE_TAG }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:${{ env.IMAGE_TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/brain-tumor-predictor:latest





